### ISSUE TITLE
Adopt new TestUtils lib in Edge extensions

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#468]
### Epic description

Scope:
- Add the new AEPTestUtils framework as a test dependency to Edge extensions
- Remove duplicated classes that are now supported by AEPTestUtils
- Adopt the common Mock/RealNetworkService from AEPTestUtils
- Adopt the new JSONAssert system for JSONs and dictionary comparisons

This applies for all existing tests for Edge extensions: unit, functional, integration.

### Tasks

- [x] https://github.com/adobe/aepsdk-edge-ios/issues/422
- [x] https://github.com/adobe/aepsdk-edge-ios/issues/430
- [x] https://github.com/adobe/aepsdk-edgeidentity-ios/issues/115
- [x] https://github.com/adobe/aepsdk-edgeconsent-ios/issues/87
- [x] https://github.com/adobe/aepsdk-edgemedia-ios/issues/41
- [x] https://github.com/adobe/aepsdk-edgebridge-ios/issues/54
