### ISSUE TITLE
Persist the XDM events

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#82]
Implement XDM events persistence for cases where there is a poor or unavailable network connection.
The events should be persisted and sent to the server in the same order they were received from the public API in current session, or in the subsequent session in case of network errors.
- [ ] Implement the DataQueueService
- [ ] Add unit tests 
- [ ] Add functional test
- [ ] Document the persistence support
