### ISSUE TITLE
XDM Shared States support

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#83]
Requirements
- ability to publish a new XDM shared state/generic context data that can be attached on each XDM experience event - to be used mainly by the core extensions.
- ability to publish an XDM shared state from any extension; the Platform extension shouldn't need to know the name of these extensions, but rather access it by xdm property name.
- ability to create data elements and run rules based on XDM shared state data.
- ability to fetch this shared state by other systems, e.g. Assurance extension or Partner extensions.
- versioned history of the data updates.

Tasks
- [x] Define the APIs
- [x] Implement client-side XDM shared state support
- [x] Add unit tests
- [x] Add functional tests
- [ ] Document the requirements for extensions intending to use the XDM Shared states - client-side, in AEP Launch, in rules
- [x] Start by using the XDM shared states in the Identity and Lifecycle extensions
