### ISSUE TITLE
Launch UI enhancements for XDM rules

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#85]
- [ ] Ability to attach/modify XDM data for client-side rules
- [ ] Add template for XDM objects
- [ ] Add optional XDM schemas list in the manifest for Launch extensions
