### ISSUE TITLE
Base end to end tests

### ISSUE THREAD

**Issue by emdobrin** [adobe/aepsdk-edge-ios#88]
- [x] Add framework support for e2e testing
- [x] Add base tests for public APIs
- [x] Write functional test(s) with response callback
